### ISSUE TITLE
User details page

### ISSUE THREAD

**Issue by orkungdk** [orkungdk/scrumier-ui#6]
# User Details Page
As a user, I should be able to see my details regarding to information that is stored in the localStorage.
- User details can be found in ``` ApplicationUser.js ```
- User details needs to be accessed in the user icon in the navigation bar
- Once user details clicked, router needs to be triggered.
- Vuetify components can be used for page design 
_____
**Note:** User icon in the navigation bar code is in the ```layouts/default.vue ```

**Comment by ayca-asaroglu** [comment]
test

**Comment by orkungdk** [comment]
@ayca-asaroglu

**Comment by ayca-asaroglu** [comment]
User details page is done. I added "My Work" button. When click on the button, it can be routing the timesheet page by filtering. When you consider this feature, you can open new task for "My Work" button.
